config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :applications, only: [:index, :show]
      resources :orders, only: [:index, :show, :create, :update] do
      	get :search, on: :collection
      end
      namespace :metrics do
        get 'all'
      end
    end
  end

  resources :applications
  resources :orders, only: [:index, :show] do
    collection do
      get  'import'
      post 'process_import'
    end
  end

  root 'orders#index'

end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :restrict_access

  private

	  def restrict_access
	    if request.method != "OPTIONS"
	      authenticate_or_request_with_http_token do |token, options|
          api_key = Application.where(auth_token: token).any? && Application.where(auth_token: token).first.active?
          @current_application = Application.where(auth_token: token).first if api_key
        end
	    end
	  end

end

app/controllers/base_controller.rb
class BaseController < ApplicationController

  http_basic_authenticate_with name: ENV["USERNAME"], password: ENV["PASSWORD"] if Rails.env.production?

end

app/views/base/_flash.html.erb
<%= content_tag :p, notice, class: 'alert alert-success' if notice.present? %>
<%= content_tag :p, alert, class: 'alert alert-danger' if alert.present? %>

app/views/base/_footer.html.erb
<div class="row footer">
  <div class="col-md-6">
    <p>© yafoy - <%= Time.now.year %></p>
  </div>
</div>

app/views/base/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "#{t 'site_name', default: 'QueenBee'}", root_path, class: "navbar-brand" %>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Recent orders', "#", id: 'toggle-push-menu' %></li>
        <li><%= link_to 'Applications', applications_path %></li>
        <li><%= link_to 'Import orders', import_orders_path %></li>
      </ul>
      <form id="global-search" action="<%= orders_path %>" method="GET" class="navbar-form navbar-right">
        <input type="text" placeholder="Search..." class="form-control" name="query"/>
      </form>
    </nav>
  </div>
</div>

app/views/base/_recent_orders.html.erb
<div class="push-menu">
  <h4>Recent orders</h4>
  <% @orders.each do |order| %>
    <div class="event">
		  <%= order.application.name.upcase %> - 
		  <b><%= number_to_currency(order.total_price, locale: order.application.locale || 'en') %></b>
		  <small><%= distance_of_time_in_words_to_now(order.date) %></small>
		  <p><%= link_to order.client_email, "#{order.url}", target: :blank %> - <%= order.city.titleize %> - <%= order.country.titleize %></p>
		</div>
  <% end %>
</div>