config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :applications, only: [:index, :show]
      resources :orders, only: [:index, :show, :create, :update] do
      	get :search, on: :collection
      end
      namespace :metrics do
        get 'all'
      end
    end
  end

  resources :applications
  resources :orders, only: [:index, :show] do
    collection do
      get  'import'
      post 'process_import'
    end
  end

  root 'orders#index'

end

app/models/application.rb
class Application < ActiveRecord::Base
	require 'identicon'

	# ASSOCIATIONS
  # ------------------------------------------------------------------------------------------------------
  has_many :orders, dependent: :destroy


  # SCOPES
  # ------------------------------------------------------------------------------------------------------
  scope :active, -> { where(active: true) }


  # VALIDATIONS
  # ------------------------------------------------------------------------------------------------------
  validates_presence_of :name, :locale
  validates_uniqueness_of :name


  # CALLBACKS
  # ------------------------------------------------------------------------------------------------------
  before_create :format_fields


  # INSTANCE METHODS
  # ------------------------------------------------------------------------------------------------------

  private

    def format_fields
  	  self.auth_token = SecureRandom.hex
      self.identicon  = Identicon.data_url_for name, 128, [255, 255, 255]
      self.slug       = I18n.transliterate(slug.present? ? slug : name).parameterize.downcase
    end

end

app/controllers/api/v1/applications_controller.rb
module Api
  module V1
    class ApplicationsController < Api::BaseController

      respond_to :json

      # curl http://localhost:3010/api/applications -H 'Authorization: Token token="111"'
      def index
        @applications = Application.order('name').limit(20)
      end

      # curl http://localhost:3010/api/applications/:id -H 'Authorization: Token token="111"'
      def show
        @application = Application.find(params[:id])

        # To use caching storage such as memcached
        # https://devcenter.heroku.com/articles/rack-cache-memcached-rails31
        # http://railscasts.com/episodes/380-memcached-dalli
        # if stale?(@application)
        #   render json: @application
        # end
      end

      private

        def safe_params
          params.require(:application).permit()
        end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < BaseController
	before_action :set_application, only: [:show, :edit, :update, :destroy]
	before_action :set_locale,      only: :show

  def index
  	@applications = Application.order('name').limit(20)
  end

  def new
  	@application = Application.new
  end

  def edit
  end

  def show
    # let's define time period for orders
    start_date = params[:start_date] || 7.days.ago
    end_date   = params[:end_date] || Time.zone.now

    # Initialize service
    service = OrderWidgets.new(@application, start_date, end_date)
    @orders = service.orders

    # Widgets
    ## Simple stats
    @orders_size   = @orders.length
    @orders_avg    = service.orders_average
    @total_revenue = service.total_revenue
    @daily_average = service.daily_revenue_average
  	@min_order     = service.min_price
    @max_order     = service.max_price
  	@avg_order     = service.average_price
    @products_avg  = service.products_average
    @referral      = service.referral

    ## Graphs
    @revenue           = service.revenue
    @monthly_revenue   = service.monthly_revenue
    @orders_count      = service.orders_count
    @average_price     = service.orders_average_price
    @most_used_coupons = service.most_used_coupons
    @revenue_by_coupon = service.revenue_by_coupon
    @sources           = service.sources
    @products_count    = service.products_count
    @top_clients       = service.top_clients
    @top_countries     = service.top_countries
    @top_cities        = service.top_cities
    @referrals         = service.referral

    if @application.subscription_based?
      # render SaaS-specific stats.
    end

    # Recent orders
    @orders = @application.orders.order('date DESC').limit(20)

    respond_to do |format|
      format.html
      format.json { render json: @application, location: api_application_url(@application) }
    end
  end

  def create
    @application = Application.new(safe_params)

    respond_to do |format|
      if @application.save
        CoreMetrics.new(@application).process
        format.html { redirect_to applications_url, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @application.update(safe_params)
        format.html { redirect_to applications_url, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_locale
      I18n.locale = @application.locale || I18n.default_locale
    end

    def set_application
    	@application = Application.includes(:orders).find(params[:id])
    end

    def safe_params
    	params.require(:application).permit(:name, :locale, :subscription_based, :active)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def page_title(title, &block)
    page_actions = block_given? ? capture(&block) : ''
    content_tag(:div, class: "page-title") do
      content_tag(:h1, (title + page_actions).html_safe)
    end
  end

  def page_section(title)
    content_tag(:div, class: "page-section") do
      content_tag(:h3, title.html_safe)
    end
  end

  def submit_or_cancel(form, submit_name = "", cancel_name="#{t 'cancel'}")
    unless submit_name.blank?
      form.submit(submit_name, class: 'btn btn-primary', data: {disable_with: "#{t 'please_wait'}"}) + " #{t 'or'} " + link_to(cancel_name, 'javascript:history.go(-1);', class: 'cancel')
    else
      form.submit(class: 'btn btn-primary', data: {disable_with: "#{t 'please_wait'}"}) + " #{t 'or'} " + link_to(cancel_name, 'javascript:history.go(-1);', class: 'cancel')
    end
  end

  CURRENCIES_SUPPORTED = [ ['English', 'en'], ['English (Canada)', 'en-CA'], ['Français', 'fr'], ['Québec', 'fr-CA'] ]

end

app/views/applications/_form.html.erb
<%= simple_form_for @application do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-md-6">
    	<%= f.input :name %>
    </div>
    <div class="col-md-6">
      <%= f.input :locale, collection: ApplicationHelper::CURRENCIES_SUPPORTED %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :subscription_based, as: :radio_buttons, collection: [['Subscription-based (recurring revenue)', true], ['Classic e-commerce store', false]] %>
    </div>
    <div class="col-md-6">
      <%= f.input :active, as: :radio_buttons %>
    </div>
  </div>

	<div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
	</div>
<% end %>

app/views/applications/_graph_widgets.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-reverse">
		  <div class="panel-heading">
		    <h3 class="panel-title">Net Revenue (by day)
		    	<i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Daily Net Revenue"></i></h3>
		  </div>
		  <div class="panel-body">
		  	<h2><%= number_to_currency @daily_average %> <small>(average daily revenue)</small></h2>
		    <%= area_chart @revenue %>
		  </div>
		</div>
  </div>

  <div class="col-md-12">
    <div class="panel panel-reverse">
		  <div class="panel-heading">
		    <h3 class="panel-title">Net Revenue (by month)
		    	<i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Monthly Net Revenue"></i></h3>
		  </div>
		  <div class="panel-body">
		    <%= column_chart @monthly_revenue %>
		  </div>
		</div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-reverse">
		  <div class="panel-heading">
		    <h3 class="panel-title">Count of Orders
		    	<i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Count of orders by day"></i></h3>
		  </div>
		  <div class="panel-body">
		  	<h2><%= @orders_size %> <small>(total)</small></h2>
		  	<h2><%= @orders_avg %> <small>(average per day)</small></h2>
		    <%= area_chart @orders_count %>
		  </div>
		</div>
  </div>

  <div class="col-md-12">
    <div class="panel panel-reverse">
		  <div class="panel-heading">
		    <h3 class="panel-title">Average Amount
		    	<i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Orders average amount (total price)"></i></h3>
		  </div>
		  <div class="panel-body">
		  	<h2><%= number_to_currency @avg_order %></h2>
		    <%= area_chart @average_price %>
		  </div>
		</div>
  </div>

  <div class="col-md-6">
    <div class="panel panel-reverse">
		  <div class="panel-heading">
		    <h3 class="panel-title">Orders by Source
		    	<i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Orders count by source"></i></h3>
		  </div>
		  <div class="panel-body">
		    <%= column_chart @sources %>
		  </div>
		</div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-reverse">
		  <div class="panel-heading">
		    <h3 class="panel-title">Clients with most orders
		    	<i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Top 10 clients based on orders count (not orders price)"></i></h3>
		  </div>
		  <div class="panel-body">
		    <%= bar_chart @top_clients %>
		  </div>
		</div>
  </div>

  <div class="col-md-6">
    <div class="panel panel-reverse">
		  <div class="panel-heading">
		    <h3 class="panel-title">Coupon Redemption
		    	<i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Most redeemed coupon codes"></i></h3>
		  </div>
		  <div class="panel-body">
		    <%= column_chart @most_used_coupons %>
		  </div>
		</div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-reverse">
		  <div class="panel-heading">
		    <h3 class="panel-title">Revenue by Coupon
		    	<i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Revenue generated by coupon code"></i></h3>
		  </div>
		  <div class="panel-body">
		    <%= column_chart @revenue_by_coupon %>
		  </div>
		</div>
  </div>

  <div class="col-md-6">
    <div class="panel panel-reverse">
		  <div class="panel-heading">
		    <h3 class="panel-title">Top Countries
		    	<i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Orders count by country"></i></h3>
		  </div>
		  <div class="panel-body">
		    <%= geo_chart @top_countries %>
		  </div>
		</div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-reverse">
		  <div class="panel-heading">
		    <h3 class="panel-title">Top Cities
		    	<i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Orders count by city"></i></h3>
		  </div>
		  <div class="panel-body">
		    <%= bar_chart @top_cities, stacked: true %>
		  </div>
		</div>
  </div>

  <div class="col-md-6">
    <div class="panel panel-reverse">
		  <div class="panel-heading">
		    <h3 class="panel-title">Products Count
		    	<i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Orders products count"></i></h3>
		  </div>
		  <div class="panel-body">
		  	<h3><%= @products_avg.round(2) %> <small>(products per order average)</small></h3>
		    <%= column_chart @products_count %>
		  </div>
		</div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-reverse">
      <div class="panel-heading">
        <h3 class="panel-title">Referral
          <i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Top partners/referral sources"></i></h3>
      </div>
      <div class="panel-body">
        <h3><%= @referral %></h3>
        <%= column_chart @referral %>
      </div>
    </div>
  </div>
</div> <!-- end row -->

app/views/applications/_price_widgets.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="panel panel-reverse">
		  <div class="panel-heading">
		    <h3 class="panel-title">Net Revenue
		    	<i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Gross Volume (Recurring and Non-recurring)"></i></h3>
		  </div>
		  <div class="panel-body">
		    <h2><%= number_to_currency(@total_revenue) %></h2>
		  </div>
		</div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-reverse">
		  <div class="panel-heading">
		    <h3 class="panel-title">Min. Amount
		    	<i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Lowest amount based on total price"></i></h3>
		  </div>
		  <div class="panel-body">
		    <h2><%= number_to_currency(@min_order) %></h2>
		  </div>
		</div>
  </div>
	<div class="col-md-3">
    <div class="panel panel-reverse">
		  <div class="panel-heading">
		    <h3 class="panel-title">Average Amount
		    <i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Average amount based on total price"></i></h3>
		  </div>
		  <div class="panel-body">
		    <h2><%= number_to_currency(@avg_order) %></h2>
		  </div>
		</div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-reverse">
		  <div class="panel-heading">
		    <h3 class="panel-title">Max. Amount
		    <i class="has-popover glyphicon glyphicon-info-sign pull-right" data-toggle="tooltip" data-placement="bottom" title="Highest amount based on total price"></i></h3>
		  </div>
		  <div class="panel-body">
		    <h2><%= number_to_currency(@max_order) %></h2>
		  </div>
		</div>
  </div>
</div>

app/views/applications/edit.html.erb
<%= page_title('Editing application') %>

<%= render 'form' %>

app/views/applications/index.html.erb
<%= page_title 'Applications' do %>
  <%= link_to "New application", new_application_path, class: 'btn-outline pull-right' %>
<% end %>

<table class="table table-light">
  <thead>
    <tr>
	  	<th>Name</th>
	    <th>Status</th>
	    <th>Token</th>
	    <th>Total orders</th>
	  </tr>
  </thead>

  <tbody>
    <% @applications.each do |app| %>
      <tr>
        <td><%= image_tag(app.identicon, size: '20x20') if !app.identicon.blank? %> <%= link_to app.name, application_path(app) %></td>
        <td><%= status_tag app.active? ? 'Active' : 'Inactive', level: app.active? ? 'default' : 'danger' %></td>
        <td><%= app.auth_token %></td>
        <td><%= app.orders_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/applications/new.html.erb
<%= page_title 'New application' %>

<%= render 'form' %>

app/views/applications/show.html.erb
<%= page_title(@application.name) do %>
  <%= status_tag(pluralize(@application.orders_count, 'order'), level: :default) %>
  <%= link_to 'Edit', edit_application_path(@application), class: 'btn-outline pull-right' %>
<% end %>

<p class="text-right nav-links">
  <small>
    <%= link_to 'Today', application_path(@application, start_date: Date.today, end_date: Date.today) %>
    <%= link_to '7d', application_path(@application, start_date: 7.days.ago.to_date, end_date: Date.today) %>
    <%= link_to '30d', application_path(@application, start_date: 30.days.ago.to_date, end_date: Date.today) %>
    <%= link_to '3m', application_path(@application, start_date: 3.months.ago.to_date, end_date: Date.today) %>
    <%= link_to '6m', application_path(@application, start_date: 6.months.ago.to_date, end_date: Date.today) %>
    <%= link_to '12m', application_path(@application, start_date: 12.months.ago.to_date, end_date: Date.today) %>
  </small>
</p>

<%= render 'price_widgets' %>
<%= render 'graph_widgets' %>

<br><br><br>
<ul>
  <li>Average order price country | city</li>
  <li>Month-to-month comparison
  - Growth
  - Time to reach if subscription</li>
  <li>Prevision CA based on growth</li>
  <li>Monthly Recurring Revenue</li>
  <li>Lifetime Value</li>
  <li>User Churn</li>
  <li>Annual Run Rate</li>
  <li>Net Revenue (revenue - fees)</li>
  <li>Total Fees</li>
  <li>Active Customers</li>
  <li>Cancelled Accounts</li>
  <li>Average Revenue Per User</li>
  <li>Revenue Growth Rate</li>
  <li>Customer Growth Rate</li>
  <li>ARPU Growth Rate</li>
  <li>Failed Charges</li>
  <li>Refunds</li>
  <li>Revenue Lost to Coupons</li>
  <li>Downgrades</li>
  <li>Upgrades</li>
  <li>Per-plan Customer Count</li>
  <li>Per-plan LTV</li>
  <li>Per-plan Churn</li>
  <li>Per-plan Gross Revenue</li>
  <li>Per-plan Fees</li>
</ul>

<% if @orders.any? %>
  <%= content_for :sidebar do %>
	  <%= render 'recent_orders', orders: @orders %>
	<% end %>
<% end %>