config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :applications, only: [:index, :show]
      resources :orders, only: [:index, :show, :create, :update] do
      	get :search, on: :collection
      end
      namespace :metrics do
        get 'all'
      end
    end
  end

  resources :applications
  resources :orders, only: [:index, :show] do
    collection do
      get  'import'
      post 'process_import'
    end
  end

  root 'orders#index'

end

app/models/order.rb
class Order < ActiveRecord::Base

	# SEARCH
  # ------------------------------------------------------------------------------------------------------
  include PgSearch
  # multisearchable :against => [:uid, :date, :client_email, :country, :city, :gift, :coupon_code]
  pg_search_scope :search_by_keyword,
                  :against => [:uid, :client_email, :country, :city, :coupon_code, :keywords],
                  :using => {
                    :tsearch => {
                      :prefix => true # match any characters
                    }
                  },
                  :ignoring => :accents


  # ASSOCIATIONS
  # ------------------------------------------------------------------------------------------------------
  belongs_to :application, counter_cache: true


  # SCOPES
  # ------------------------------------------------------------------------------------------------------
  scope :by_month,         -> (month)    { where("date BETWEEN '#{month.beginning_of_month}' AND '#{month.end_of_month}'") }
  scope :by_day,           -> (day)      { where("date BETWEEN '#{day.beginning_of_day}' AND '#{day.end_of_day}'") }
  scope :within_period,    -> (from, to) { where(date: (from..to)) }
  scope :from_date,        -> (from)     { where("date >= ?", from) }
  scope :to_date,          -> (to)       { where("date <= ?", to) }
  scope :recurring,        -> { where.not(subscribed_at: nil) }
  scope :recurring_active, -> { where.not(subscribed_at: nil).where(unsubscribed_at: nil) }
  scope :unsubscribed,     -> { where.not(unsubscribed_at: nil, subscribed_at: nil) }
  scope :with_referral,    -> { where.not(referral: nil) }


  # VALIDATIONS
  # ------------------------------------------------------------------------------------------------------
  validates_presence_of :uid, :date, :amount, :shipping, :total_price, :country,
   	                    :city, :client_email
  validates_presence_of :currency, unless: Proc.new{ |o| o.application.locale.present? }
  validates_uniqueness_of :uid, scope: :application_id


  # CALLBACKS
  # ------------------------------------------------------------------------------------------------------
  before_save :format_fields, :sync_keywords
  after_save :sync_metrics


  # INSTANCE METHODS
  # ------------------------------------------------------------------------------------------------------
  def self.import_file(file)
    allowed_attributes = [ 'uid', 'client_email', 'country', 'city', 'products_count',
                           'date', 'currency', 'amount', 'shipping', 'total_price', 'gift',
                           'coupon', 'coupon_code', 'url', 'tax', 'source' ]
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      order = find_by_id(row['id']) || new
      order.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
      order.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.csv'  then     Roo::Csv.new(file.path, nil, :ignore)
    when '.xls'  then  Roo::Excel.new(file.path,  nil, :ignore)
    when '.xlsx' then Roo::Excelx.new(file.path,  nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  private

    def format_fields
      self.currency     = currency.present? ? currency.downcase : application.try(:default_currency)
    	self.country      = country.downcase if country
    	self.city         = city.downcase if city
      self.client_email = client_email.downcase.strip if client_email
      self.week_day     = date.to_date.cwday if date
      self.month_day    = date.day if date
      self.hour         = date.to_time.hour if date
      self.uid          = uid.strip if uid
    end

    def sync_keywords
      keywords = []
      keywords << self.date.strftime("%d/%m/%Y")
      keywords << self.application.name.downcase.to_s
      self.keywords = keywords.join(", ")
    end

    def sync_metrics
      CoreMetrics.new(application).process
    end
end

app/controllers/api/v1/orders_controller.rb
module Api
  module V1
    class OrdersController < Api::BaseController
      before_action :set_order, only: [:show, :update]

      respond_to :json

      # curl http://localhost:3010/api/orders -H 'Authorization: Token token="111"'
      def index
        now = Time.zone.now.beginning_of_day
        start_date = params[:start_date] || now.beginning_of_day - 7.days
        end_date   = params[:end_date] || now.end_of_day
        @orders = @current_application.orders.within_period(start_date, end_date).order('date DESC')
        render json: @orders, status: 200
      end

      # curl http://localhost:3010/api/orders/:id -H 'Authorization: Token token="111"'
      def show
        render json: @order, status: 200
      end

      # curl -v -H 'Authorization: Token token="111"' -H "Content-type: application/json" -X POST -d '{"order": {"date": "2014-07-01 14:50:28", "currency": "CAD", "city": "Paris", "country": "Canada", "client_email": "d@email.com", "uid": "0000099"}}' http://localhost:3010/api/orders
      def create
        @order = @current_application.orders.new(safe_params)

        if @order.save
          render json: @order, status: :created
        else
          render json: @order.errors.full_messages.to_sentence, status: 422
        end
      end

      def update
        if @order.present?
          if @order.update(safe_params)
            render :show, status: :ok, location: @order
          else
            render json: @order.errors.full_messages.to_sentence, status: :unprocessable_entity
          end
        else
          render json: "Order Not Found", status: :not_found
        end
      end

      private

        def safe_params
          params.require(:order).permit(:uid, :client_email, :country, :city, :products_count,
                                        :date, :currency, :amount, :shipping, :total_price, :gift,
                                        :coupon, :coupon_code, :url, :tax, :source, :subscribed_at,
                                        :unsubscribed_at, :fees, :referral)
        end

        def set_order
          @order = @current_application.orders.find_by(uid: params[:id])
        end

    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < BaseController

  def index
    @applications = Application.active.order('name')
  	if params[:query].present?
  		@orders = Order.search_by_keyword(params[:query]).limit(20)
    else
      orders = Order.within_period(Date.today.beginning_of_year, Date.today)
      @orders = orders.order('date DESC').limit(20)
  	end
    @orders_by_day = Order.group_by_day(:date, range: 30.days.ago.midnight..Date.today).count
  end

  def show
  	@order = Order.find(params[:id])
  end

  def import
  end

  def process_import
    if params[:file].present?
      app = Application.find(params[:application_id])
      app.orders.import_file(params[:file])
      redirect_to import_orders_url, notice: 'Orders were successfully imported.'
    else
      redirect_to import_orders_url, alert: 'Please select a file to import.'
    end
  end

end

app/views/orders/_graphs.html.erb
<div class="page-section">
  <ul class="nav tabs-section" role="tablist">
    <li role="presentation" class="active"><a href="#week" id="week-tab" role="tab" data-toggle="tab" aria-controls="week" aria-expanded="false">This Week</a></li>
    <li role="presentation" class=""><a href="#month" role="tab" id="month-tab" data-toggle="tab" aria-controls="month" aria-expanded="true">This Month</a></li>
    <li role="presentation" aria-expanded="false"><a href="#year" role="tab" id="year-tab" data-toggle="tab" aria-controls="year" aria-expanded="true">This Year</a></li>
  </ul>
</div>

<div class="tab-content">
  <div role="tabpanel" class="tab-pane fade" id="week" aria-labelledby="week-tab">
    <div class="row">
      <% @applications.each do |app| %>
        <div class="col-md-3 mb4">
          <div class="widget-graph">
            <div class="widget">
              <% serie = app.metrics["net_revenue"]["this_week"] %>
              <span class="widget-title">
                <%= app.name %>
              </span>
              <h2>
                <%= number_to_currency(serie["value"] || 0, locale: app.locale) %>
                <small class="<%= (serie['percentage_change'].to_f || 0) > 0 ? 'positive' : 'negative' %>"><%= number_to_percentage(serie["percentage_change"] || 0, precision: 2) %></small>
              </h2>
            </div>
            <canvas id="sparkline1" width="358" height="89" class="apu" data-chart="spark-line" data-value="[{strokeColor: '#1ca8dd', fillColor:'rgba(28,168,221,.03)', data:[28,68,41,43,96,45,100]}]" data-labels="['a', 'b','c','d','e','f','g']" style="width: 358px; height: 89px;"></canvas>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div role="tabpanel" class="tab-pane fade active in" id="month" aria-labelledby="month-tab">
    <div class="row">
      <% @applications.each do |app| %>
        <div class="col-md-3 mb4">
          <div class="widget-graph">
            <div class="widget">
              <% serie = app.metrics["net_revenue"]["this_month"] %>
              <span class="widget-title">
                <%= app.name %>
              </span>
              <h2>
                <%= number_to_currency(serie["value"] || 0, locale: app.locale) %>
                <small class="<%= (serie['percentage_change'].to_f || 0) > 0 ? 'positive' : 'negative' %>"><%= number_to_percentage(serie["percentage_change"] || 0, precision: 2) %></small>
              </h2>
            </div>
            <canvas id="sparkline1" width="358" height="89" class="apu" data-chart="spark-line" data-value="[{strokeColor: '#1ca8dd', fillColor:'rgba(28,168,221,.03)', data:[28,68,41,43,96,45,100]}]" data-labels="['a', 'b','c','d','e','f','g']" style="width: 358px; height: 89px;"></canvas>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div role="tabpanel" class="tab-pane fade" id="year" aria-labelledby="year-tab">
    <div class="row">
      <% @applications.each do |app| %>
        <div class="col-md-3 mb4">
          <div class="widget-graph">
            <div class="widget">
              <% serie = app.metrics["net_revenue"]["this_year"] %>
              <span class="widget-title">
                <%= app.name %>
              </span>
              <h2>
                <%= number_to_currency(serie["value"] || 0, locale: app.locale) %>
                <small class="<%= (serie['percentage_change'].to_f || 0) > 0 ? 'positive' : 'negative' %>"><%= number_to_percentage(serie["percentage_change"] || 0, precision: 2) %></small>
              </h2>
            </div>
            <canvas id="sparkline1" width="358" height="89" class="apu" data-chart="spark-line" data-value="[{strokeColor: '#1ca8dd', fillColor:'rgba(28,168,221,.03)', data:[28,68,41,43,96,45,100]}]" data-labels="['a', 'b','c','d','e','f','g']" style="width: 358px; height: 89px;"></canvas>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/import.html.erb
<%= page_title('Import orders from file') %>

<p class="alert alert-info">Make sure to download our <%= link_to "sample file", "/sample_orders.xlsx", class: 'alert-link' %> to get started.</p>

<%= form_tag process_import_orders_path, multipart: true do %>
  <%= select_tag 'application_id', options_from_collection_for_select(Application.order('name'), 'id', 'name') %>
  <div class="form-group">
    <%= file_field_tag :file %>
    <p class="help-block">Only Excel files are supported.</p>
  </div>
  <div class="form-actions">
  	<%= submit_tag 'Import', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/orders/index.html.erb
<%= page_title "Dashboard" %>
<%= page_section "Today" %>

<div class="row">
  <% @applications.each do |app| %>
    <div class="col-md-3 mb4">
      <div class="widget-graph">
        <div class="widget">
          <% serie = app.metrics["net_revenue"]["today"] %>
          <span class="widget-title">
            <%= app.name %>
          </span>
          <h2>
            <%= number_to_currency(serie["value"] || 0, locale: app.locale) %>
            <small class="<%= (serie['percentage_change'].to_f || 0) > 0 ? 'positive' : 'negative' %>"><%= number_to_percentage(serie["percentage_change"] || 0, precision: 2) %></small>
          </h2>
        </div>
        <canvas id="sparkline1" width="358" height="89" class="apu" data-chart="spark-line" data-value="[{strokeColor: '#1ca8dd', fillColor:'rgba(28,168,221,.03)', data:[28,68,41,43,96,45,100]}]" data-labels="['a', 'b','c','d','e','f','g']" style="width: 358px; height: 89px;"></canvas>
      </div>
    </div>
  <% end %>
</div>

<%= render 'graphs' %>

<h4>Orders count by day</h4>
<%= area_chart @orders_by_day %>

<% if @orders.any? %>
  <%= content_for :sidebar do %>
    <%= render 'recent_orders', orders: @orders %>
  <% end %>
<% end %>

app/views/orders/index_save.html.erb
<delayed-search ng-model="filterCriteria"></delayed-search>
<span>{{filterCriteria}}</span>

<input type="text" ng-model="searchOrder" ng-change="change(text)" placeholder="Search for order" class="form-control input-lg" name="searchOrder"/>

<table class="table table-light">
  <thead>
    <tr>
	  	<th>Source</th>
	    <th>Date</th>
	    <th>Total Amount</th>
	    <th>UID</th>
	    <th>Location</th>
	  </tr>
  </thead>

  <tbody>
    <tr ng-repeat="order in orders">
      <td>{{ order.source }}</td>
      <td>{{ order.date }}</td>
      <td>{{ order.total_price }} {{ order.currency | uppercase }}</td>
      <td>{{ order.uid }}</td>
      <td>{{ order.city }} - {{ order.country }}</td>
    </tr>
  </tbody>
</table>